include(
        "common",
        "main",
        "testbot",
        "test-samples",
        ":extensions:youtube-rotator",
        ":extensions:format-xm",
        "natives",
        "natives-publish"
)