name: Publish
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup Java
                uses: actions/setup-java@v3
                with:
                    distribution: zulu
                    java-version: 11
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Build and Publish
                run: ./gradlew build publish --no-daemon -PMAVEN_USERNAME=$MAVEN_USERNAME -PMAVEN_PASSWORD=$MAVEN_PASSWORD

            -   name: Upload Artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: Lavaplayer.zip
                    path: |
                        main/build/libs/lavaplayer-*.jar
                        common/build/libs/lava-common-*.jar
                        extensions/format-xm/build/libs/lavaplayer-ext-format-xm-*.jar
                        extensions/youtube-rotator/build/libs/lavaplayer-ext-youtube-rotator-*.jar
                        natives-publish/build/libs/lavaplayer-natives-*.jar

    release:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'release'
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Download main Artifact
                uses: actions/download-artifact@v3
                with:
                    name: Lavaplayer.zip

            -   name: Upload Artifacts to GitHub Release
                uses: ncipollo/release-action@v1
                with:
                    artifacts: |
                        main/build/libs/lavaplayer-*.jar
                        common/build/libs/lava-common-*.jar
                        extensions/format-xm/build/libs/lavaplayer-ext-format-xm-*.jar
                        extensions/youtube-rotator/build/libs/lavaplayer-ext-youtube-rotator-*.jar
                        natives-publish/build/libs/lavaplayer-natives-*.jar
                    allowUpdates: true
                    omitBodyDuringUpdate: true
                    omitDraftDuringUpdate: true
                    omitNameDuringUpdate: true
                    omitPrereleaseDuringUpdate: true
