name: Release

on:
    release:
        types: [published]

jobs:
    build:
        uses: ./.github/workflows/build.yml
        secrets:
            MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

    publish-natives:
        uses: ./.github/workflows/build-natives.yml
        secrets:
            MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
    release:
        needs:
            [build, publish-natives]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                  name: Lavaplayer.zip

            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                  name: Lavaplayer-Natives.zip

            - name: Upload Artifacts to GitHub Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: |
                      main/build/libs/lavaplayer-*.jar
                      common/build/libs/lava-common-*.jar
                      extensions/format-xm/build/libs/lavaplayer-ext-format-xm-*.jar
                      extensions/youtube-rotator/build/libs/lavaplayer-ext-youtube-rotator-*.jar
                  allowUpdates: true
                  omitBodyDuringUpdate: true
                  omitDraftDuringUpdate: true
                  omitNameDuringUpdate: true
                  omitPrereleaseDuringUpdate: true
